ansible_user: root
ansible_python_interpreter: /opt/local/bin/python2

nics:
  - {interface: "net0", nic_tag: "external", vlan_id: "3", ip: "10.0.3.15", netmask: "255.255.255.0", gateway: "10.0.3.1"}
filesystems:
  - {source: "/zones/data/personal", target: "/media/personal", read_only: false}
  - {source: "/zones/data/media/movies", target: "/media/movies", read_only: false}
  - {source: "/zones/data/media/tv", target: "/media/tv", read_only: false}
  - {source: "/zones/data/media/incoming", target: "/media/incoming", read_only: false}
  - {source: "/zones/data/training", target: "/media/training", read_only: false}
  - {source: "/zones/data/music", target: "/media/music", read_only: false}
