- name: Install postgresql
  package: name={{ item }} state=present
  with_items:
    - postgresql94-server
    - postgresql94-adminpack
- name: Enable postgresql
  service: name=postgresql state=started enabled=yes
