# ansible-playbook -i ../hosts  playbook.yml 
- hosts: samba 
  vars:
    ansible_python_interpreter: /opt/local/bin/python2
    ip: 10.0.3.15
  remote_user: root
  gather_facts: no
  tasks:
  - include: ../smartos_bootstrap.yml
  - name: add users
    user: name={{ item }} state=present uid=1000 password=$1$Salty$os1z.HuWt0cmUJeIfNeX1. groups=adm
    with_items:
     - piranha
  - authorized_key: user=piranha key=https://github.com/precurse.keys
  - authorized_key: user=root key=https://github.com/precurse.keys
  - name: Unlock Account
    command: passwd -N piranha
  - name: ensure samba installed
    pkgin: name=samba state=present
  - name: ensure samba is running (and enable it at boot)
    service: name={{ item }} state=started enabled=yes
    with_items:
      - samba:smbd
      - samba:nmbd 
  - template:
      src=smb.conf.j2 dest=/opt/local/etc/samba/smb.conf owner=root group=root mode=0644 
  - name: Set Timezone
    command: sm-set-timezone MST
  - name: Samba Setup
    shell: (echo password; echo password) | smbpasswd -a -s piranha
    tags:
      - setup
  - service: name={{ item }} state=restarted
    with_items:
      - samba:smbd
      - samba:nmbd 
