- hosts: samba 
  vars:
    ansible_python_interpreter: /opt/local/bin/python2
  remote_user: root
  tasks:
  - name: add users
    user: name={{ item }} state=present uid=1000 groups=adm
    with_items:
     - piranha
  - authorized_key: user=piranha key=https://github.com/precurse.keys
  - authorized_key: user=root key=https://github.com/precurse.keys
  - name: ensure samba installed
    pkgin: name=samba state=present
  - name: ensure samba is running (and enable it at boot)
    service: name={{ item }} state=started enabled=yes
    with_items:
      - samba:smbd
      - samba:nmbd 
  - template: src=smb.conf.j2 dest=/opt/local/etc/samba/smb.conf owner=root group=root mode=0644 
  - name: Set Timezone
    command: sm-set-timezone MST
  - name: Samba Setup
    command: echo -ne "password\npassword\n" | smbpasswd -a -s piranha 
    tags:
      - setup
  - service: name={{ item }} state=restarted
    with_items:
      - samba:smbd
      - samba:nmbd 

