# ansible-playbook -i ../hosts  provision-vm.yml -c local
- hosts: smartos
  vars:
    hypervisor_ip: 10.0.3.2
    hypervisor_user: root
    autoboot: "true"
    image_uuid: c540b62c-beb2-11e5-8512-8b1694a57f84  # minimal-64-lts
    cpu_cap: 100
    max_phy_mem: 1024
    quota: 100
    brand: joyent
    alias: smb
    domain: signet
    ip: 10.0.3.15
    resolver: 10.0.3.1
    gateway: 10.0.3.1
    subnet: 255.255.255.0
    vlan_id: 3
    first_script: "/usr/sbin/mdata-get root_authorized_keys > ~root/.ssh/authorized_keys ; /usr/sbin/mdata-get root_autho
rized_keys > ~admin/.ssh/authorized_keys"
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCX5NmP23FhXZ+YiV3unu/Bz6h5oaeJyx3J5EaJOi4de0im3MV1aXZlpYnF0MfpmRxYl2S2pUEJXjW/toA48A+zYjHI7xReKZ9MpCsDBlW4Vfl6EjaoZqN3Hc4P5wK/BiMkSIgURFRJukus1ajRvV+YZiAaRyTwgkhmF20ZdOOIAPiugaoEYg+6iQ5CJZURw1VLJ+UViCC7cBcC4AOjKcbEaLf9RzjISzAs78fN7G60+P5fyAsIinDhKC2VJE/AkxjFtQAdBlt3HNhWnLfd2jmClRNA24Ob/gL3i3OWecWdEsERSypDiOFZI/sRHDKih1mkESbiZiHHMiZRCO34Fqpx piranha@laptop"
    ansible_python_interpreter: /usr/bin/python2.7
  remote_user: root
  tasks:
  - local_action: command mktemp /tmp/ansible.XXXXXXX
    register: tmp_json
  - local_action: template src=smartos_template.json.j2 dest={{ tmp_json.stdout }}
  - local_action: shell /usr/bin/ssh {{ hypervisor_user }}@{{ hypervisor_ip }} imgadm import {{ image_uuid }}
  - local_action: shell cat {{ tmp_json.stdout }} | /usr/bin/ssh {{ hypervisor_user }}@{{ hypervisor_ip }} vmadm create 
