# ansible-playbook -i ../hosts  provision-vm.yml -c local
- hosts: smartos
  vars:
    hypervisor_ip: 10.0.3.2
    hypervisor_user: root
    autoboot: "true"
    image_uuid: c540b62c-beb2-11e5-8512-8b1694a57f84  # minimal-64-lts
    cpu_cap: 100
    max_phy_mem: 1024
    quota: 100
    brand: joyent
    alias: smb
    domain: signet
    ip: 10.0.3.15
    resolver: 10.0.3.1
    gateway: 10.0.3.1
    subnet: 255.255.255.0
    vlan_id: 3
    ansible_python_interpreter: /usr/bin/python2.7
  vars_files:
    - ../smartos_vars.yml
  remote_user: root
  tasks:
  - local_action: command mktemp /tmp/ansible.XXXXXXX
    register: tmp_json
  - local_action: template src=smartos_template.json.j2 dest={{ tmp_json.stdout }}
  - local_action: shell /usr/bin/ssh {{ hypervisor_user }}@{{ hypervisor_ip }} imgadm import {{ image_uuid }}
  - local_action: shell cat {{ tmp_json.stdout }} | /usr/bin/ssh {{ hypervisor_user }}@{{ hypervisor_ip }} vmadm create 
