- name: Download certbot-auto
  get_url:
    url: https://raw.githubusercontent.com/certbot/certbot/master/certbot-auto
    dest: /root/certbot-auto
    mode: 0755
  become: yes

- name: Create invalid tmp cert/key to start haproxy (to bootstrap new haproxy install)
  shell: "{{ item }}"
  args:
    chdir: /tmp
    creates: "{{ haproxy_cb_dest_bundle }}"
  with_items:
    - "openssl genrsa -out server.key 2048"
    - "openssl req -new -key server.key -out server.csr -subj '/C=GB/ST=London/L=London/O=Global Security/OU=IT Department/CN=example.com'"
    - "openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt"
    - "cat server.crt server.key > {{ haproxy_cb_dest_bundle }}"
  become: yes

- name: Ensure haproxy started
  service:
    name: haproxy
    state: started
  become: yes

- name: Create certbot certs if needed
  command: "/root/certbot-auto {{ haproxy_cb_certonly_flags }}"
  become: yes

- name: Setup certbot crontab if needed
  cron: name="Autorenew certbot"
        special_time="daily"
        job="/root/certbot-auto {{ haproxy_cb_renew_flags }}"
        cron_file=certbot
        user="root"
  become: yes
