- name: Install python-pip
  package:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - py27-pip
    - gcc49

- name: Install certbot from pip
  pip:
    name: certbot
    state: present
  become: yes

- name: Create tmp cert/key to start haproxy (First time run only)
  shell: "{{ item }}"
  args:
    chdir: /tmp
    creates: /opt/local/etc/haproxy.pem
  with_items:
    - "openssl genrsa -out server.key 2048"
    - "openssl req -new -key server.key -out server.csr -subj '/C=GB/ST=London/L=London/O=Global Security/OU=IT Department/CN=example.com'"
    - "openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt"
    - "cat server.crt server.key > /opt/local/etc/haproxy.pem"
  become: yes

# - name: Combine certs + key for haproxy
#   shell: "cat /etc/letsencrypt/live/{{ haproxy_cb_domains[0] }}/{fullchain,privkey}.pem > /opt/local/etc/haproxy.pem"
#   ignore_errors: yes
#   become: yes


- name: Ensure haproxy started
  service:
    name: haproxy
    state: started

- name: Create certbot certs if needed
  command: certbot certonly \
          --debug \
          --standalone \
          --preferred-challenges tls-sni-01 \
          --tls-sni-01-port 18443 \
          --agree-tos \
          --email {{ haproxy_cb_email }} \
          --keep-until-expiring \
          --quiet \
          --expand \
          -n \
          {% for i in haproxy_cb_domains %} -d {{ i }} {% endfor %} \
          --post-hook "{{ haproxy_cb_posthook }}"

- name: Setup certbot crontab if needed
  cron: name="Autorenew certbot"
        special_time="hourly"
        job="certbot renew --keep-until-expiring -q -n --preferred-challenges tls-sni-01 --tls-sni-01-port 18443 --debug --post-hook '{{ haproxy_cb_posthook }}'"
        cron_file=certbot
        user="root"
