- name: Ensure group present
  group:
    name: "{{ haproxy_group }}"
    state: present
  become: yes

- name: Ensure user present
  user:
    name: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    state: present
  become: yes

- name: Install haproxy
  yum:
    name: haproxy
    state: present
    update_cache: yes
  become: yes

- name: Copy haproxy template
  template:
    src: haproxy.conf.j2
    dest: "{{ haproxy_conf }}"
  become: yes
  notify: reload haproxy
  tags: config

- name: Ensure chroot dir created
  file:
    path: "{{ haproxy_chroot_dir }}"
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    state: directory
    mode: 0644
  become: yes

- name: Setup certbot
  include: install_certbot.yml

- name: Enable haproxy
  service:
    name: haproxy
    state: started
    enabled: yes
  become: yes

- name: Download haproxy exporter
  get_url:
    url: https://github.com/prometheus/haproxy_exporter/releases/download/v{{ haproxy_exporter_version }}/haproxy_exporter-{{ haproxy_exporter_version }}.linux-amd64.tar.gz
    dest: /root/haproxy_exporter-{{ haproxy_exporter_version }}.linux-amd64.tar.gz
  become: yes

- name: Extract haproxy exporter
  unarchive:
    remote_src: true
    src: haproxy_exporter-{{ haproxy_exporter_version }}.linux-amd64.tar.gz
    dest: /root/
  become: yes

- name: Setup haproxy exporter on startup
  lineinfile:
    path: /etc/rc.local
    regexp: '^/root/haproxy_exporter'
    insertbefore: 'exit 0'
    line: '/root/haproxy_exporter-{{ haproxy_exporter_version }}.linux-amd64/haproxy_exporter --haproxy.scrape-uri="http://{{ haproxy_stats_user }}:{{ haproxy_stats_pass }}@localhost:8082/haproxy?stats;csv" &'
  become: yes


