- name: Ensure group present
  group:
    name: haproxy
    state: present
  become: yes

- name: Ensure user present
  user:
    name: haproxy
    group: haproxy
    state: present
  become: yes

- name: Copy haproxy template
  template:
    src: haproxy.conf.j2
    dest: /opt/local/etc/haproxy.cfg
  become: yes

- name: Install haproxy
  pkgin:
    name: haproxy
    state: present
    update_cache: yes
  become: yes

- name: Ensure chroot dir created
  file:
    path: /var/lib/haproxy
    state: directory
    owner: haproxy
    group: haproxy
    mode: 0644
  become: yes

- name: Setup certbot
  include: install_certbot.yml

- name: Enable haproxy
  service:
    name: haproxy
    state: started
    enabled: yes
  become: yes
