- name: Ensure group present
  group:
    name: "{{ haproxy_group }}"
    state: present
  become: yes

- name: Ensure user present
  user:
    name: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    state: present
  become: yes

- name: Copy haproxy template
  template:
    src: haproxy.conf.j2
    dest: "{{ haproxy_conf }}"
  become: yes

- name: Install haproxy
  pkgin:
    name: haproxy
    state: present
    update_cache: yes
  become: yes

- name: Ensure chroot dir created
  file:
    path: "{{ haproxy_chroot_dir }}"
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    state: directory
    mode: 0644
  become: yes

- name: Setup certbot
  include: install_certbot.yml

- name: Enable haproxy
  service:
    name: haproxy
    state: started
    enabled: yes
  become: yes
