- name: Update packages
  yum: name=* state=latest
  tags: update_packages
- name: Add influxdb key 
  rpm_key: state=present key=https://repos.influxdata.com/influxdb.key

- name: Add yum repo
  template: src=influxdb.repo.j2 dest=/etc/yum.repos.d/influxdb.repo owner=root group=root

- name: Install influxdb
  package: name=influxdb state=present
- name: Influxdb config
  template: src=influxdb.conf.j2 dest=/etc/influxdb/influxdb.conf owner=root group=root mode=0644 
- name: Enable influxdb service
  service: name=influxdb state=running enabled=yes
