- hosts: nginx 
  vars:
    https_port: 443
    http_port: 80 
    ansible_python_interpreter: /opt/local/bin/python2
  remote_user: root
  tasks:
  - name: install building utils
    pkgin: name=gcc47 state=present
  - name: ensure nginx installed
    pkgin: name=nginx state=present
  - name: ensure nginx is running (and enable it at boot)
    service: name=nginx state=started enabled=yes
  - name: install letsencrypt dependencies 1
    pkgin: name=py27-virtualenv state=present
  - name: install letsencrypt dependencies 2  
    pkgin: name=py27-pip state=present
  - name: install letsencrypt dependencies 3
    pkgin: name=py27-augeas state=present
  - name: install letsencrypt dependencies 4 
    pkgin: name=py27-dialog state=present
  - name: install letsencrypt dependencies 5
    pkgin: name=py27-pip state=present
  - name: install letsencrypt dependencies 6
    pkgin: name=augeas state=present 
  - pip: name=letsencrypt
  - template: src=nginx.conf.j2 dest=/opt/local/etc/nginx/nginx.conf owner=root group=root mode=0644
  - template: src=letsencrypt.ini.j2 dest=/etc/letsencrypt/cli.ini owner=root group=root mode=0644 
  - template: src=automate-letsencrypt.sh.j2 dest=/root/automate-letsencrypt.sh owner=root group=root mode=0644 
  - name: Set Timezone
    command: sm-set-timezone MST
    tags:
      - setup
  - name: Letsencrypt Setup
    command: letsencrypt certonly --renew-by-default --agree-tos
    tags:
      - setup
  - name: generate dhparam.pem file
    command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096 
    tags:
      - setup
  - cron: name="Letsencrypt renewal" day="1" job="/root/automate-letsencrypt.sh" 
  - service: name=nginx state=reloaded

