- name: Update apt
  apt: update_cache=yes
- name: Update packages
  apt: upgrade=dist update_cache=yes
  tags: update_packages
- name: Adding https apt support
  package: name=apt-transport-https state=present
- name: Add grafana key
  apt_key: url=https://packagecloud.io/gpg.key state=present
- name: Add grafana repo
  apt_repository: repo='deb https://packagecloud.io/grafana/stable/debian/ wheezy main' state=present
- name: Install grafana
  package: name=grafana state=present
- name: Enable grafana service
  service: name=grafana-server state=running enabled=yes

