- name: Update packages
  yum: name=* state=latest
  tags: update_packages
- name: Add grafana key
  rpm_key: state=present key=https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
- name: Add grafana repo
  template: src=grafana.repo.j2 dest=/etc/yum.repos.d/grafana.repo owner=root group=root
- name: Install grafana
  package: name=grafana state=present
- name: Enable grafana service
  service: name=grafana-server state=running enabled=yes

