- hosts: dbserver
  remote_user: root
  gather_facts: no
  tasks:
  - include: tasks/smartos_zone_bootstrap.yml
  - include: tasks/smartos_zone_usersetup.yml
  - name: Install postgresql
    package: name=postgresql94-server state=latest
