- hosts: all
  gather_facts: true
  tasks:
     - group_by: key=os_{{ ansible_distribution }}
       tags: update_packages

- hosts: os_CentOS
  gather_facts: False
  roles:
    - enable_autoupdate

- hosts: os_Debian
  gather_facts: False
  roles:
    - enable_autoupdate

- hosts: os_Ubuntu
  gather_facts: False
  roles:
    - enable_autoupdate
