- hosts: influxdb
  remote_user: root
  gather_facts: no
  tasks:
    - name: Update packages
      apt: upgrade=dist update_cache=yes
      tags: update_packages
    - name: Install influxdb
      package: name=influxdb state=latest
