- hosts: plex
  remote_user: root
  gather_facts: no
  roles:
    - smartos_provision
    - common
    - plex
#    - zabbix_agent
  vars:
    autoboot: "true"
    image_name: centos-6
    cpu_cap: 400
    max_phy_mem: 1024
    quota: 20
    brand: lx
    alias: plex
    domain: signet
    nics:
      - {interface: "eth0", nic_tag: "external", vlan_id: "4", ip: "10.0.4.11", netmask: "255.255.255.0", gateway: "10.0.4.1"}
    filesystems:
      - {source: "/zones/db/plex", target: "/var/lib/plexmediaserver", read_only: false}
      - {source: "/zones/data/media", target: "/media", read_only: true}
