# file: site.yml

- hosts: all
  gather_facts: false
  roles:
    - role: smartos_provision
  vars:
    - provision_mode: true
    - smartos_python_path: /opt/local/bin/python2
  post_tasks:
    # Install python on joyent zones
    - block:
        - name: Upgrading pkgin packages
          raw: /opt/local/bin/pkgin -y update; /opt/local/bin/pkgin -y upgrade
        - name: Installing python
          raw: /opt/local/bin/pkgin -y install python27
        - set_fact: ansible_python_interpreter={{ smartos_python_path }}
        - name: Test python install
          setup:
      rescue:
        - debug: msg="Unable to install python on joyent zone"

      when: brand == 'joyent'
      become: yes

