# file: provision_vm.yml 

- hosts: smartos
  gather_facts: no
  vars:
    hypervisor_ip: 10.0.3.2
    hypervisor_user: root
    autoboot: "true"
    image_uuid: c540b62c-beb2-11e5-8512-8b1694a57f84  # minimal-64-lts
    cpu_cap: 100
    max_phy_mem: 256
    quota: "20"
    brand: joyent
    alias: nginx
    domain: signet
    ip: 10.0.4.12
    resolver: 10.0.4.1
    gateway: 10.0.4.1
    subnet: 255.255.255.0
    vlan_id: 4
    ansible_python_interpreter: /usr/bin/python2.7
  vars_files:
    - ../smartos_vars.yml
  remote_user: root
  roles:
    - smartos_hypervisor
  tasks:
  - local_action: command mktemp /tmp/ansible.XXXXXXX
    register: tmp_json
  - local_action: template src=smartos_template.json.j2 dest={{ tmp_json.stdout }}
  - local_action: shell /usr/bin/ssh {{ hypervisor_user }}@{{ hypervisor_ip }} imgadm import {{ image_uuid }}
  - local_action: shell cat {{ tmp_json.stdout }} | /usr/bin/ssh {{ hypervisor_user }}@{{ hypervisor_ip }} vmadm create 


- hosts: shell
  gather_facts: no
  remote_user: root
  vars:
    - ALIAS: shell
  roles:
    - role: smartos_provision
  tasks:
  - include_vars: roles/shell/vars/main.yml
    when: ALIAS == 'shell'
 
  - local_action: command mktemp /tmp/ansible.XXXXXXX
    register: tmp_json
  - local_action: template src=smartos_template.json.j2 dest={{ tmp_json.stdout }}
  - local_action: shell /usr/bin/ssh {{ hypervisor_user }}@{{ hypervisor_ip }} imgadm import {{ image_uuid }}
  - local_action: shell cat {{ tmp_json.stdout }} | /usr/bin/ssh {{ hypervisor_user }}@{{ hypervisor_ip }} vmadm create 
