# ansible-playbook -i ../hosts  playbook.yml 
- hosts: samba 
  remote_user: root
  gather_facts: no  
  roles:
    - role: smartos_provision
    - role: common
    - role: samba
  vars:
    nics:
      - {interface: "net0", nic_tag: "external", vlan_id: "3", ip: "10.0.3.15", netmask: "255.255.255.0", gateway: "10.0.3.1"}
    filesystems:
      - {source: "/zones/data/personal", target: "/media/personal", read_only: false}
      - {source: "/zones/data/media/movies", target: "/media/movies", read_only: false}
      - {source: "/zones/data/media/tv", target: "/media/tv", read_only: false}
      - {source: "/zones/data/media/incoming", target: "/media/incoming", read_only: false}
      - {source: "/zones/data/training", target: "/media/training", read_only: false}
      - {source: "/zones/data/music", target: "/media/music", read_only: false}


  tasks:
  - name: ensure samba installed
    pkgin: name=samba state=present
  - name: ensure samba is running (and enable it at boot)
    service: name={{ item }} state=started enabled=yes
    with_items:
      - samba:smbd
      - samba:nmbd 
  - template:
      src=smb.conf.j2 dest=/opt/local/etc/samba/smb.conf owner=root group=root mode=0644 
  - name: Samba Setup
    shell: (echo password; echo password) | smbpasswd -a -s piranha
    tags:
      - setup
  - service: name={{ item }} state=restarted
    with_items:
      - samba:smbd
      - samba:nmbd 
