- hosts: kim
  become: true
  roles:
    - { role: common, tags: common }
    - { role: haproxy_kim, tags: haproxy }
    - { role: ssmtp, tags: ssmtp }
    - { role: docker, tags: docker }
    - { role: precurse.kim_docker_images, tags: docker }
