- hosts: samba
  gather_facts: no
  roles:
    - common
    - samba
  tasks:
  - name: ensure samba installed
    pkgin: name=samba state=present
  - name: ensure samba is running (and enable it at boot)
    service: name={{ item }} state=started enabled=yes
    with_items:
      - samba:smbd
      - samba:nmbd 
  - template:
      src=smb.conf.j2 dest=/opt/local/etc/samba/smb.conf owner=root group=root mode=0644 
  - name: Samba Setup
    shell: (echo password; echo password) | smbpasswd -a -s piranha
    tags:
      - setup
  - service: name={{ item }} state=restarted
    with_items:
      - samba:smbd
      - samba:nmbd
