- hosts: shell
  remote_user: root
  gather_facts: no
  roles:
    - role: smartos_provision
    - role: joyent_zone_bootstrap
    - role: common
  vars:
    autoboot: "true"
    image_name: minimal-64-lts
    cpu_cap: 100
    max_phy_mem: 256
    quota: 5
    brand: joyent
    alias: shell 
    domain: signet
    nics:
      - {interface: "net0", nic_tag: "external", vlan_id: "4", ip: "10.0.4.10", netmask: "255.255.255.0", gateway: "10.0.4.1"}
