# file: site.yml

#- include: plexmission.yml
- include: shell.yml
- include: samba.yml
- include: ups.yml
- include: nginx.yml
- include: freebsd.yml
- include: syncthing.yml
- include: dbserver.yml
- include: elasticsearch.yml
- include: influxdb.yml
- include: owncloud.yml
- include: plexmission.yml
- include: subsonic.yml
