# file: site.yml

- hosts: shell
  gather_facts: no
  roles:
    - role: smartos_provision
    - role: joyent_zone_bootstrap
    - role: common

- hosts: zabbix_server
  roles:
    - smartos_provision
    - common
    - zabbix_server

- hosts: ldap
  remote_user: root
  gather_facts: no
  roles:
    - role: smartos_provision
    - role: common
    - role: openldap

- hosts: kim
  remote_user: piranha
  become: true
  roles:
    - common

- hosts: pimon
  roles:
    - common
    - ups
    - pxeserver

- hosts: owncloud
  roles:
    - smartos_provision
    - common
  tasks:
    - name: Adding https apt support
      package: name=apt-transport-https state=present
    - name: Add owncloud repos
      apt_repository: repo='deb https://download.owncloud.org/download/repositories/stable/Debian_8.0/ /' state=present

- hosts: plex
  remote_user: root
  roles:
    - smartos_provision
    - common
    - plex

- hosts: transmission
  roles:
    - smartos_provision
    - common
    - transmission

- hosts: syncthing
  remote_user: root
  roles:
    - role: smartos_provision
    - role: common

- hosts: subsonic
  roles:
    - role: smartos_provision
    - role: common
    - role: subsonic

- hosts: nginx 
  tasks:
  - include: tasks/smartos_zone_bootstrap.yml
  - include: tasks/smartos_zone_usersetup.yml
  - name: install building utils
    pkgin: name=gcc47 state=present
  - name: ensure nginx installed
    pkgin: name=nginx state=present
  - name: ensure nginx is running (and enable it at boot)
    service: name=nginx state=started enabled=yes
  - name: install letsencrypt dependencies
    pkgin: name={{ item }} state=present
    with_items:
      - py27-pip
      - augeas
  - pip: name=letsencrypt
  - template: src=nginx.conf.j2 dest=/opt/local/etc/nginx/nginx.conf owner=root group=root mode=0644
  - template: src=letsencrypt.ini.j2 dest=/etc/letsencrypt/cli.ini owner=root group=root mode=0644 
  - template: src=automate-letsencrypt.sh.j2 dest=/root/automate-letsencrypt.sh owner=root group=root mode=0644 
  - name: Set Timezone
    command: sm-set-timezone MST
    tags:
      - setup
  - name: Letsencrypt Setup
    command: letsencrypt certonly --renew-by-default --agree-tos
    tags:
      - setup
  - name: generate dhparam.pem file (Be prepared to wait)
    command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096 
    tags:
      - setup
  - cron: name="Letsencrypt renewal" day="1" job="/root/automate-letsencrypt.sh" 
  - service: name=nginx state=reloaded

- hosts: samba 
  gather_facts: no  
  roles:
    - role: smartos_provision
    - role: common
    - role: samba
  tasks:
  - name: ensure samba installed
    pkgin: name=samba state=present
  - name: ensure samba is running (and enable it at boot)
    service: name={{ item }} state=started enabled=yes
    with_items:
      - samba:smbd
      - samba:nmbd 
  - template:
      src=smb.conf.j2 dest=/opt/local/etc/samba/smb.conf owner=root group=root mode=0644 
  - name: Samba Setup
    shell: (echo password; echo password) | smbpasswd -a -s piranha
    tags:
      - setup
  - service: name={{ item }} state=restarted
    with_items:
      - samba:smbd
      - samba:nmbd 
