# file: site.yml
- hosts: all
  roles:
    - common

- include: setup_pimon.yml
- include: setup_webproxy.yml
- include: setup_samba.yml
- include: setup_owncloud.yml
- include: setup_plex.yml
- include: setup_subsonic.yml
- include: setup_transmission.yml

- hosts: git
  roles:
    - git_server

- hosts: ceph
  tasks:
    - name: Create ceph group
      group: name=ceph
    - name: Create ceph user
      user:
        name=ceph
        state=present
        groups=ceph
    - name: Add cep repository
      yum_repository:
        name: ceph-noarch
        description: Ceph noarch packages
        baseurl: https://download.ceph.com/rpm-{{ ceph_release }}/{{ distro }}/noarch
        gpgcheck: yes
        gpgkey: https://download.ceph.com/keys/release.asc
    - name: Update yum repos
      yum:
        name=ceph-deploy
        state=present


- hosts: dbserver
  roles:
#    - joyent_zone_bootstrap
    - postgresql

- hosts: zabbix_server
  roles:
    - zabbix_server

- hosts: ldap
  remote_user: root
  gather_facts: no
  roles:
    - openldap

- hosts: kim
  remote_user: piranha
  become: true
  roles:
    - openvpn


- hosts: syncthing
  remote_user: root
  roles:
    - common


- hosts: influxdb
  remote_user: root
  gather_facts: no
  roles:
    - common
    - influxdb
    - grafana
