# file: site.yml

- include: shell.yml
- include: samba.yml
- include: ups.yml
- include: pxe.yml
- include: nginx.yml
- include: freebsd.yml
- include: syncthing.yml
- include: dbserver.yml
- include: elasticsearch.yml
- include: influxdb.yml
- include: owncloud.yml
- include: plex.yml
- include: transmission.yml
- include: subsonic.yml
