- name: Ensure ssmtp installed
  apt:
    name: ssmtp
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Setup ssmtp template
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
  become: yes
