- name: Ensure consul user exists
  user:
    name: consul
    comment: "Consul user"
    shell: /bin/false
    state: present

- name: Ensure unzip binary exists
  package:
    name: unzip
    state: present
  become_user: consul
  become: true

- name: Check if consul already installed
  stat:
    path: /usr/local/sbin/consul
  register: st_c

- block:
  - include: download_consul.yml

  - name: Extract consul
    unarchive:
      src: /tmp/consul_{{ consul_ver }}.zip
      dest: /usr/local/sbin
      remote_src: True
    become: true
    notify: restart consul
  when: st_c.stat.executable is not defined or not st_c.stat.executable

- name: Ensure consul.d directory exists
  file:
    path: /etc/consul.d
    state: directory
    mode: 0755
  notify: restart consul
  become: true

- name: Ensure consul data directory exists and proper permissions
  file:
    path: /var/lib/consul
    state: directory
    mode: 0755
    recurse: yes
    owner: consul
    group: consul
  become: true

## Systemd
- block:
  - name: setup systemd service file
    template:
      src: templates/consul.service.j2
      dest: /etc/systemd/system/consul.service
    become: true

  - name: Setup consul systemd service
    systemd:
      name: consul
      daemon_reload: yes
      state: started
      enabled: yes
    become: true
  when: ansible_service_mgr == "systemd"
## /Systemd

## SysVInit
#- block:
#  - name: setup sysvinit consul file
#
#  when: ansible_service_mgr == "sysvinit"
