- name: Install cups
  pacman:
    name={{ item }}
    update_cache=yes
    state=present
  with_items:
    - cups
    - ghostscript
    - gsfonts
  become: yes

- name: Configure cupsd.conf
  template:
    src=templates/cupsd.conf.j2
    dest=/etc/cups/cupsd.conf
  become: yes
  notify: restart cups

- name: Ensure username part of sys group
  user:
    name=alarm
    groups=sys
  become: yes

- name: Start services
  service:
    name={{ item }}
    state=started
    enabled=yes
  with_items:
    - org.cups.cupsd
    - cups-browsed
  become: yes
