
haproxy_cb_email: user@example.com
haproxy_cb_domains:
  - www.example.com
  - example.com

haproxy_cb_prehook: ""
haproxy_cb_posthook: "cat /etc/letsencrypt/live/{{ haproxy_cb_domains[0] }}/{fullchain,privkey}.pem > /opt/local/etc/haproxy.pem; svcadm restart haproxy"

