silk_user: silk
silk_group: silk

silk_no_yaf: true
silk_yaf_interface: eth0

silk_tmp_dir: /home/{{ silk_user }}/tmp
silk_data_dir: /data
# Latest version/hashes from:
  # http://tools.netsa.cert.org/fixbuf/download.html
  # http://tools.netsa.cert.org/yaf/download.html
  # http://tools.netsa.cert.org/silk/download.html
silk_lfb_ver: 1.7.1
silk_lfb_sha256: 961296ed000d4fdb4ae8690613bba2af2e4d634c044f947795abc24e9caf644a
silk_lfb_fn: libfixbuf-{{ silk_lfb_ver }}.tar.gz
silk_lfb_url: http://tools.netsa.cert.org/releases/{{ silk_lfb_fn }}

silk_yaf_ver: 2.8.4
silk_yaf_sha256: 4ce75938de40f2a27dcc360ac6a4930e55e9d5c1bd27fd77e4c66fd48faa8d02 
silk_yaf_fn: yaf-{{ silk_yaf_ver }}.tar.gz
silk_yaf_url: http://tools.netsa.cert.org/releases/{{ silk_yaf_fn  }}

silk_silk_ver: 3.14.0
silk_silk_sha256: a871fa74de79e79c4d81220edf225ae4e2c596a9f500a572e228156976ac7e6e
silk_silk_fn: silk-{{ silk_silk_ver }}.tar.gz
silk_silk_url: http://tools.netsa.cert.org/releases/{{ silk_silk_fn }}

silk_geoip_url: http://geolite.maxmind.com/download/geoip/database/GeoIPCountryCSV.zip
silk_geoip_cron: True

silk_probes:
  - name: S0
    protocol: udp
    address: "{{ ansible_default_ipv4.address }}"
    port: 9988
    type: netflow-v9
  - name: S1
    protocol: udp
    address: "{{ ansible_default_ipv4.address }}"
    port: 5600
    type: sflow

silk_networks:
  - name: my_net
    ipblocks:
      - 192.168.0.0/16
      - 10.0.0.0/8

silk_sensors:
  - name: S0
    type: netflow-v9
    probe: S0
    internal_network: my_net
  - name: S1
    type: sflow
    probe: S1
    internal_network: my_net

