- name: Update apt cache
  apt: update_cache=yes

- name: Update packages
  apt: upgrade=dist update_cache=yes
  tags: update_packages

- name: Installing openjdk
  package: name=openjdk-7-jre state=present

- name: Check for subsonic.deb file
  stat: path=/subsonic.deb
  register: debfile

- name: Download subsonic
  get_url: url={{ subsonic_url }}
    dest="/subsonic.deb"
  when: debfile.stat.md5 is not defined

- name: Install subsonic
  apt: deb="/subsonic.deb" state=present

