- name: Install packags
  package: name={{ item }} state=present
  with_items:
    - python-cheetah
    - unrar-free
    - git
    - curl
    - git-core
    - build-essential
    - libsqlite3-dev
    - libbz2-dev
    - libreadline-dev
    - libssl-dev
    - zlib1g-dev

- name: Create sickgear user
  user:
    name: sickgear
    state: present

- name: Clone sickgear repo
  git:
    repo: https://github.com/sickgear/sickgear.git
    dest: /opt/sickgear

- name: Clone pyenv repo
  git:
    repo: https://github.com/yyuu/pyenv
    dest: /opt/sickgear/.pyenv

- name: Change repo directory perms
  file:
    path: /opt/sickgear
    recurse: yes
    owner: sickgear
    group: sickgear

- name: Install pyenv Python
  shell: PYENV_ROOT=/opt/sickgear/.pyenv /opt/sickgear/.pyenv/bin/pyenv install 2.7.11
  args:
    creates: /opt/sickgear/.pyenv/versions/2.7.11
  become_user: sickgear
  become: true

- name: Install sickgear dependencies
  shell: /opt/sickgear/.pyenv/versions/2.7.11/bin/pip install -r requirements.txt
  args:
    chdir: /opt/sickgear
  become_user: sickgear
  become: true

- name: Copy sickgear init
  copy:
    remote_src: true
    src: /opt/sickgear/init-scripts/init.debian
    dest: /etc/init.d/sickgear
    mode: 0755
  become: true

- name: Make sickgear init defaults
  lineinfile:
    dest=/etc/default/sickgear
    regexp="^\.*PYTHON_BIN="
    line="PYTHON_BIN=/opt/sickgear/.pyenv/versions/2.7.11/bin/python"
  become: true

- name: More sickgear init defaults
  lineinfile:
    dest=/etc/default/sickgear
    regexp="^\.*RUN_AS="
    line="RUN_AS=sickgear"
  become: true

- name: Start sickgear on startup
  service:
    name: sickgear
    state: started
    enabled: yes
  become: true
