- name: gather facts
  setup:

- block:
  - name: Setup Users
    user:
      name: piranha
      state: present
      groups: "{{ admin_group }}"

  - name: Adding github ssh keys
    authorized_key: user={{ item }} key=https://github.com/precurse.keys
    with_items:
      - piranha
      - root

  - name: Enable account
    command: passwd -N piranha
    when: ansible_distribution == "SmartOS"

  - name: Enable EPEL Repo for CentOS		
    yum:
      name: epel-release
      state: present
    when: ansible_distribution == "CentOS"

  - name: Enable SCL Repo for CentOS		
    yum:
      name: centos-release-SCL
      state: present		
    when: ansible_distribution == "CentOS"

  - name: Disable Debian auto-start daemons on install
    shell: echo "exit 101" > /usr/sbin/policy-rc.d creates=/usr/sbin/policy-rc.d
    when: ansible_os_family == "Debian"

  - name: Install common packages
    package: name={{ item }} state=present
    with_items:
      - sudo
      - tmux
    ignore_errors: yes

  - name: Setting hostname on SmartOS
    command: sm-set-hostname {{ alias }}
    when: alias is defined and ansible_distribution == "SmartOS"
    changed_when: no

  - name: Setting hostname on Linux	
    hostname: name={{ alias }}		
    when: alias is defined and ansible_system == "Linux"
    changed_when: no
  become: yes
