- name: gather facts    
  setup:
- name: Setup Users
  user: name=piranha state=present groups={{ admin_group }}
- name: Adding github ssh keys
  authorized_key: user={{ item }} key=https://github.com/precurse.keys
  with_items:
    - piranha
    - root
- name: Enable account
  command: passwd -N piranha
  when: ansible_distribution == "SmartOS"

- name: Disable Debian auto-start daemons on install
  shell: echo "exit 101" > /usr/sbin/policy-rc.d creates=/usr/sbin/policy-rc.d
  when: ansible_os_family == "Debian" 

- name: Install common packages
  package: name={{ item }} state=present
  with_items:
    - sudo
    - tmux
  ignore_errors: yes
