- name: Ensure pre-requesite packages installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  become: yes

- name: Ensure Docker apt-key setup
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Enable docker apt repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
  become: yes

- name: Ensure docker installed
  apt:
    name: docker-ce
    cache_valid_time: 3600
    state: present
  become: yes

- name: Ensure docker enabled at boot
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
