# http://www.htpcguides.com/install-plex-media-server-on-debian-linux/
- hosts: plexmission
  remote_user: root
  tasks:
  - name: add several users
    user: name={{ item }} state=present uid=1000 groups=sys
    with_items:
     - piranha
  - authorized_key: user=piranha key=https://github.com/precurse.keys
  - authorized_key: user=root key=https://github.com/precurse.keys
  - apt_key: url=http://shell.ninthgate.se/packages/shell-ninthgate-se-keyring.key state=present
  - apt_repository: repo='deb http://www.deb-multimedia.org wheezy main non-free' state=present filename='deb_multimedia'
  - apt_repository: repo='deb http://shell.ninthgate.se/packages/debian wheezy main' state=present filename='plex'
  - name: install packages 
    apt: package={{ item }} state=latest update_cache=yes 
    with_items:
      - transmission-daemon
      - plexmediaserver
      - deb-multimedia-keyring
  - name: ensure transmission-daemon is running (and enable it at boot)
    service: name=transmission-daemon state=started enabled=yes 
  - name: ensure plexmediaserver is running (and enable it at boot)
    service: name=plexmediaserver state=started enabled=yes
