# Debian/Ubuntu specifics
- block:
  - name: Ensure apt-transport-https package installed
    apt:
      name: apt-transport-https
      state: present
      cache_valid_time: 3600
    become: yes

  - name: Add syncthing apt key
    apt_key:
      url: https://syncthing.net/release-key.txt
      state: present
    become: yes

  - name: Add syncthing apt repo
    apt_repository:
      repo: deb https://apt.syncthing.net/ syncthing release
      state: present
    become: yes

  - name: Install syncthing
    apt:
      name: syncthing
      state: present
      update_cache: yes
    become: yes

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# Arch specifics
- name: Install syncthing (Arch)
  pacman:
    name: syncthing
    state: present
    update_cache: yes
  when: ansible_distribution == 'Archlinux'


- name: Ensure syncthing group exists
  group:
    name: "{{ st_user }}"
    state: present
  become: yes

- name: Ensure syncthing user exists
  user:
    name: "{{ st_user }}"
    group: "{{ st_user }}"
    state: present
  become: yes

- name: Copy syncthing init script
  template:
    src: templates/syncthing.init.j2
    dest: /etc/init.d/syncthing
    mode: 0755
  become: yes
  when: ansible_service_mgr == 'sysvinit'

- name: Ensure default store folder writable
  file:
    state: directory
    recurse: true
    path: "{{ st_def_folder }}"
    owner: "{{ st_user }}"
  become: yes

- name: Ensure external storage folder writable
  file:
    state: directory
    recurse: true
    path: "{{ filesystems[0].target }}"
    owner: "{{ st_user }}"
  become: yes
  when: filesystems is defined and filesystems

# Do stuff as syncthing user
- block:
  - name: Ensure syncthing config dir exists
    file:
      state: directory
      path: /home/{{ st_user }}/.config/syncthing/

  - name: Setup syncthing config template
    template:
      src: config.xml.j2
      dest: /home/{{ st_user }}/.config/syncthing/config.xml
      force: no
  become_user: "{{ st_user }}"
  become: yes

- name: Enable syncthing service (init)
  service:
    name: syncthing
    state: started
    enabled: yes
  become: yes
  when: ansible_service_mgr == 'sysvinit'

- name: Enable syncthing service (systemd)
  service:
    name: syncthing@{{ st_user }}
    state: started
    enabled: yes
  become: yes
  when: ansible_service_mgr == 'systemd'
