- name: Create haproxy_exporter user
  user:
    name: haexport
    comment: HAProxy Exporter
  become: yes

- name: Create /opt/haproxy_exporter-0.9.0
  file:
    path: /opt/haproxy_exporter-0.9.0
    state: directory
  become: true

- name: Download haproxy_exporter
  get_url:
    url: https://github.com/prometheus/haproxy_exporter/releases/download/v0.9.0/haproxy_exporter-0.9.0.linux-amd64.tar.gz
    dest: /tmp/haproxy_exporter-0.9.0.linux-amd64.tar.gz
  become: yes

- name: Extract haproxy_exporter
  unarchive:
    src: /tmp/haproxy_exporter-0.9.0.linux-amd64.tar.gz
    dest: /opt/haproxy_exporter-0.9.0
    remote_src: true
  become: yes

- name: Copy init script
  template:
    src: haproxy-exporter.init
    dest: /etc/init.d/prometheus-haproxy-exporter
    mode: 0755
  become: yes

- name: Copy init defaults
  template:
    src: haproxy-defaults.init
    dest: /etc/default/prometheus-haproxy-exporter
  become: yes

- name: Enable haproxy-exporter  on startup
  service:
    name: prometheus-haproxy-exporter
    state: started
    enabled: yes
  become: yes
