- name: Install haproxy
  apt:
    name: haproxy
    state: present
    update_cache: yes
  become: yes

- name: Copy ca certificate
  copy:
    content: "{{ ca_pem }}"
    dest: "{{ ca_pem_file }}"
  become: yes

- name: Setup haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  become: yes
  notify: reload haproxy

- name: Ensure haproxy started and on boot
  service:
    name: haproxy
    state: started
    enabled: yes
  become: yes

- include: haproxy-exporter.yml
