- name: Install openvpn
  pacman:
    name: openvpn
    update_cache: yes
    state: present
  become: yes

- name: Copy crts/key
  copy:
    src=files/{{ item }}
    dest="{{ openvpn_server_dir }}/{{ item }}"
  with_items:
    - ca.crt
    - server.crt
    - server.key
  become: yes

- name: setup ta.key
  shell: openvpn --genkey --secret ta.key
  args:
    creates: "{{ openvpn_server_dir }}/ta.key"
    chdir: "{{ openvpn_server_dir }}"
  become: yes

- name: setup dhparam
  shell: openssl dhparam -out dh2048.pem 2048
  args:
    creates: "{{ openvpn_server_dir }}/dh2048.pem"
    chdir: "{{ openvpn_server_dir }}"
  become: yes

- name: Set file permissions for secret files
  file:
    path="{{ openvpn_server_dir }}/{{ item }}"
    mode=0600
    owner=root
    group=root
  with_items:
    - ta.key
    - dh2048.pem
    - server.key
  become: yes

- name: Install openvpn template
  template:
    src=templates/server.conf.j2
    dest="{{ openvpn_server_dir }}/server.conf"
  become: yes
