- name: Copy crts/key
  copy:
    src=files/{{ item }}
    dest=/etc/openvpn/{{ item }}
  with_items:
    - ca.crt
    - server.crt
    - server.key
  become: yes

- name: setup ta.key
  shell: openvpn --genkey --secret ta.key
  args:
    creates: /etc/openvpn/ta.key
    chdir: /etc/openvpn

- name: setup dhparam
  shell: openssl dhparam -out dh2048.pem 2048
  args:
    creates: /etc/openvpn/dh2048.pem
    chdir: /etc/openvpn
  become: yes

- name: Set file permissions for secret files
  file:
    path=/etc/openvpn/{{ item }}
    mode=0600
    owner=root
    group=root
  with_items:
    - ta.key
    - dh2048.pem
    - server.key
  become: yes

- name: Install openvpn template
  template:
    src=templates/server.conf.j2
    dest=/etc/openvpn/server.conf
  become: yes
